### ISSUE TITLE
fragment pkt has invalid segment count

### ISSUE THREAD

**Issue by chrhong** [OpenDataPlane/odp#1352]
DPDK: 19.11.6
ODP version: 1.28.0.0
Pktio: DPDK, zero copy mode.
Segment fault detected wile add data to a fragmented pkt, while is splited by odp_packet_split() api.

```
Program terminated with signal SIGSEGV, Segmentation fault.
b#0  0x00007f07450f832f in free_all_segments (num=3, pkt_hdr=0x7f05c6fae410) at odp_packet.c:542
542                     seg_hdr = seg_hdr->seg_next;
#0  0x00007f07450f832f in free_all_segments (num=3, pkt_hdr=0x7f05c6fae410) at odp_packet.c:542
        i = <optimized out>
        buf_hdr = {0x7f0702c63e00, 0x7f06e36a2e40, 0x0}
        seg_hdr = 0x0
        i = <optimized out>
        buf_hdr = <optimized out>
        seg_hdr = <optimized out>
#1  odp_packet_free (pkt=pkt@entry=0x7f0702c63e00) at odp_packet.c:742
        pkt_hdr = 0x7f0702c63e00
        num_seg = 3
        __func__ = <optimized out>
#2  0x00007f07450fa55b in odp_packet_add_data (pkt_ptr=pkt_ptr@entry=0x7f05c6fae4d8, offset=offset@entry=54, len=len@entry=8) at odp_packet.c:1232
        pkt = 0x7f0702c63e00
        pkt_hdr = 0x7f0702c63e00
        pktlen = 1502
        pool = <optimized out>
        newpkt = 0x7f06dae883c0
```

Suppose this is split api bug, which cause a wrong seg count. Since the issue is hard to reproduce, I already add seg count check in odp_packet_split(). More info will be updated once the issue is reproduced.

**Comment by chrhong** [comment]
most probably same with https://github.com/OpenDataPlane/odp/issues/1532.
close it too.
